include $(CLEAR_VARS)
LOCAL_MODULE := SetupWraith
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SetupWraith.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
