/* sloane has no camera, provide dummy functions to satisfy camera libraries */
extern "C" void _ZN7android19MtkCameraParameters20PIXEL_FORMAT_YUV420IE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters19KEY_VR_BUFFER_COUNTE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters15KEY_CAMERA_MODEE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters18CAMERA_MODE_NORMALE() {/*N/A*/}
extern "C" void _ZN7android11MtkCamUtils11ImgBufQueueC1EiPKc() {/*N/A*/}
extern "C" void _ZN7android11MtkCamUtils8FmtUtils18queryImgBufferSizeEPKcjj() {/*N/A*/}
extern "C" void _ZN7android11MtkCamUtils8FmtUtils19queryImgWidthStrideEPKcjj() {/*N/A*/}
extern "C" void _ZN7android11MtkCamUtils11DevMetaInfo17queryHalSensorDevEi() {/*N/A*/}
extern "C" void _ZN7android11MtkCamUtils8FmtUtils15queryPlaneCountEPKc() {/*N/A*/}
extern "C" void _ZN7android7camera210HalEffectsC1EPFiPvPKcPS4_PiE() {/*N/A*/}
extern "C" void _ZN10hal3DFBase14createInstanceE14Hal3DFObject_s() {/*N/A*/}
extern "C" void _ZN15halAUTORAMABase14createInstanceE19HalAUTORAMAObject_s() {/*N/A*/}
extern "C" void _ZN12DpBlitStreamC1Ev() {/*N/A*/}
extern "C" void _ZN12DpBlitStream12setSrcBufferEPPvPjj() {/*N/A*/}
extern "C" void _ZN12DpBlitStream12setSrcConfigEii13DP_COLOR_ENUM17DpInterlaceFormatP6DpRect() {/*N/A*/}
extern "C" void _ZN12DpBlitStream12setDstBufferEPvj() {/*N/A*/}
extern "C" void _ZN12DpBlitStream12setDstConfigEii13DP_COLOR_ENUM17DpInterlaceFormatP6DpRect() {/*N/A*/}
extern "C" void _ZN12DpBlitStream10invalidateEv() {/*N/A*/}
extern "C" void _ZN12DpBlitStreamD1Ev() {/*N/A*/}
extern "C" void _ZN12DpBlitStream12setDstBufferEPPvPjj() {/*N/A*/}
extern "C" void _ZN18halMOTIONTRACKBase14createInstanceEv() {/*N/A*/}
extern "C" void _ZN10halASDBase14createInstanceE14HalASDObject_s() {/*N/A*/}
extern "C" void _ZN9halFDBase14createInstanceE13HalFDObject_e() {/*N/A*/}
extern "C" void _ZN9halGSBase14createInstanceE13HalGSObject_e() {/*N/A*/}
extern "C" void _ZN4NS3A9Hal3ABase14createInstanceEi() {/*N/A*/}
extern "C" void _ZN7IMemDrv14createInstanceEv() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters21PIXEL_FORMAT_YV12_GPUE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters25PIXEL_FORMAT_YUV422I_VYUYE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters25PIXEL_FORMAT_YUV422I_YVYUE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters25PIXEL_FORMAT_YUV422I_UYVYE() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters19PIXEL_FORMAT_BAYER8E() {/*N/A*/}
extern "C" void _ZN7android19MtkCameraParameters20PIXEL_FORMAT_BAYER10E() {/*N/A*/}
extern "C" void _ZN7mmutils14IGrallocHelper9singletonEv() {/*N/A*/}